name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cloud_firestore: ^3.4.2
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.3.1
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.3
  get: 4.6.5
  image_cropper: ^1.5.1
  image_picker: ^0.8.5+3
  intl_phone_number_input: ^0.7.0+2
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: "Rubik"
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
